# Databricks notebook source
# MAGIC
# MAGIC
# MAGIC
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# DBTITLE 1,Cell 2
# MAGIC %sql
# MAGIC -- drop table if exists retail.logistics.bronze_geotag
# MAGIC
# MAGIC
